name: pingpong
version: 0.1.0.0
github: "frontsideair/pingpong"
license: BSD3
author: "Fatih Altinok"
maintainer: "fatihaltinok@live.com"
copyright: "2019 Fatih Altinok"

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - monad-coroutine

library:
  source-dirs: src

executables:
  coroutines-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pingpong
